#!/bin/sh
#
# Written by Weqaar A. Janjua <weqaar.janjua@linuxiot.org>
#
### BEGIN INIT INFO
# Provides:          IoTGatewayService
# Required-Start:    
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start IoT Gateway Service at boot time
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/opt/IoTGateway
DAEMON=/opt/IoTGateway/main.py
NAME=IoTGatewayService
DESC="IoT Gateway Service"

test -x $DAEMON || exit 0

set -e

case "$1" in
  start)
	echo -n "Starting $DESC: "
	start-stop-daemon --start --verbose -m -b --pidfile /var/run/$NAME.pid \
		--oknodo --exec $DAEMON
	echo "$NAME."
	;;
  stop)
	echo -n "Stopping $DESC: "
	start-stop-daemon --stop --verbose --pidfile /var/run/$NAME.pid
	#	--oknodo --exec $DAEMON
	echo "$NAME."
	;;
  restart|force-reload)
	$0 stop
	sleep 1
	$0 start	
	;;
  *)
	N=/etc/init.d/$NAME
	echo "Usage: $N {start|stop|restart|force-reload}" >&2
	exit 1
	;;
esac

exit 0
